version: '3'

services:
  backend:
    build: ./
    working_dir: /usr/src/app
    environment:
      DB_USER: postgres
      DB_PASSWORD: H9C12500
      DB_NAME: restaurants_test
      DB_HOST: postgres
    links:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      DB_USER: postgres
      DB_PASSWORD: H9C12500
      DB_NAME: restaurants_test
      DB_HOST: postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
