version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 8000:8000
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
