version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
